#!/bin/sh

set -e

namespace=${NAMESPACE:-default}
service="$1"

if [ -z "$service" ] ; then
        echo "Usage: $0 <service>" >&2
        exit 1
fi

cacert="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"

echo Waiting for $service to have endpoints
while : ; do 
	active=$(curl --silent --cacert $cacert --header "Authorization: Bearer $token" \
		https://kubernetes.default.svc/api/v1/namespaces/$namespace/endpoints/$service \
		| jq -r '.subsets[].addresses | length')
	if [ "$active" -gt 0 ] ; then
		exit 0
	fi
        echo -n .
        sleep 2
done

